#!/usr/bin/env bash

USERNAME=voidxnull
IMAGE=zeropool-substrate-faucet

cd frontend && \
yarn && yarn build && \
cd .. && \
docker build -f Dockerfile -t $USERNAME/$IMAGE:latest . && \
docker push $USERNAME/$IMAGE:latest
